import type { ProductType } from "@/types/product"
import type { CategoryType } from "@/types/category"

// Mock products data
export const mockProducts: ProductType[] = [
  {
    productId: "1",
    name: "Modern Open Abaya",
    slug: "modern-open-abaya",
    price: 3500,
    sale_price: 2999,
    description:
      "A modern open abaya with stylish design elements. Made with high-quality Nida fabric that ensures comfort throughout the day.",
    images: [{ url: "https://assets0.mirraw.com/images/10369712/IMG_0877_long_webp.webp?1688222419", alt_text: "Modern Open Abaya", is_default: true }],
    avg_rating: 4.5,
    review_count: 28,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Navy", "Gray"],
    },
    stock_quantity: 25,
    category_id: "abayas",
    category: "Abayas",
    category_slug: "abayas",
    subcategory_id: "open-abayas",
    subcategory: "Open Abayas",
    subcategory_slug: "open-abayas",
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "OA-001",
  },
  {
    productId: "2",
    name: "Classic Closed Abaya",
    slug: "classic-closed-abaya",
    price: 4200,
    description:
      "A traditional closed abaya with contemporary touches. Perfect for those who value both tradition and modern style.",
    images: [{ url: "https://assets0.mirraw.com/images/11335745/BT-EUMA-005-Black_1_long_webp.webp?1679318935", alt_text: "Classic Closed Abaya", is_default: true }],
    avg_rating: 4.3,
    review_count: 15,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Crepe", "Georgette"],
      Color: ["Black", "Gray", "Beige"],
    },
    stock_quantity: 18,
    category_id: "abayas",
    category: "Abayas",
    category_slug: "abayas",
    subcategory_id: "closed-abayas",
    subcategory: "Closed Abayas",
    subcategory_slug: "closed-abayas",
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "CA-001",
  },
  {
    productId: "3",
    name: "Luxury Kaftan Abaya",
    slug: "luxury-kaftan-abaya",
    price: 5500,
    sale_price: 4999,
    description:
      "A luxurious kaftan-style abaya perfect for special occasions. Features intricate details and premium fabric.",
    images: [{ url: "https://assets0.mirraw.com/images/11995268/CATO-ABD-075-NAVY_BLUE_1_long_webp.webp?1698929814", alt_text: "Luxury Kaftan Abaya", is_default: true }],
    avg_rating: 4.8,
    review_count: 32,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Crepe", "Silk Blend"],
      Color: ["Navy Blue", "Burgundy", "Emerald"],
    },
    stock_quantity: 12,
    category_id: "abayas",
    category: "Abayas",
    category_slug: "abayas",
    subcategory_id: "kaftan-abayas",
    subcategory: "Kaftan Abayas",
    subcategory_slug: "kaftan-abayas",
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "KA-001",
  },
  {
    productId: "4",
    name: "Casual Maxi Dress",
    slug: "casual-maxi-dress",
    price: 2800,
    description:
      "A comfortable and stylish maxi dress perfect for everyday wear. Features a modest design with modern elements.",
    images: [{ url: "https://assets0.mirraw.com/images/11997029/ME-AB-222-PUCE_PINK_2_long_webp.webp?1698932325", alt_text: "Casual Maxi Dress", is_default: true }],
    avg_rating: 4.4,
    review_count: 24,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Cotton Blend", "Rayon"],
      Color: ["Pink", "Blue", "Green"],
    },
    stock_quantity: 30,
    category_id: "modest-maxi-dresses",
    category: "Modest Maxi & Dresses",
    category_slug: "modest-maxi-dresses",
    subcategory_id: "casual-maxi-dresses",
    subcategory: "Casual Maxi Dresses",
    subcategory_slug: "casual-maxi-dresses",
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "CMD-001",
  },
  {
    productId: "5",
    name: "Formal Maxi Dress",
    slug: "formal-maxi-dress",
    price: 4500,
    description:
      "An elegant maxi dress perfect for formal occasions. Features sophisticated design elements and premium fabric.",
    images: [{ url: "https://assets0.mirraw.com/images/5900026/AY-417-1-min_long.jpg", alt_text: "Formal Maxi Dress", is_default: true }],
    avg_rating: 4.7,
    review_count: 19,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Crepe", "Silk Blend"],
      Color: ["Black", "Navy", "Burgundy"],
    },
    stock_quantity: 15,
    category_id: "modest-maxi-dresses",
    category: "Modest Maxi & Dresses",
    category_slug: "modest-maxi-dresses",
    subcategory_id: "formal-maxi-dresses",
    subcategory: "Formal Maxi Dresses",
    subcategory_slug: "formal-maxi-dresses",
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "FMD-001",
  },
  {
    productId: "6",
    name: "Party Maxi Dress",
    slug: "party-maxi-dress",
    price: 5200,
    sale_price: 4799,
    description:
      "A stunning maxi dress perfect for special celebrations. Features elegant details and luxurious fabric.",
    images: [{ url: "https://assets0.mirraw.com/images/11149811/IMG_2841_long.JPG", alt_text: "Party Maxi Dress", is_default: true }],
    avg_rating: 4.9,
    review_count: 27,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Crepe", "Silk Blend"],
      Color: ["Emerald", "Royal Blue", "Deep Purple"],
    },
    stock_quantity: 10,
    category_id: "modest-maxi-dresses",
    category: "Modest Maxi & Dresses",
    category_slug: "modest-maxi-dresses",
    subcategory_id: "party-maxi-dresses",
    subcategory: "Party Maxi Dresses",
    subcategory_slug: "party-maxi-dresses",
    is_active: true,
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "PMD-001",
  },
  // Formal
  {
    productId: "2",
    name: "Formal Abaya",
    slug: "formal-abaya",
    price: 5000,
    description:
      "An elegant abaya designed for formal occasions and professional settings. Features refined tailoring and premium fabric for a sophisticated look.",
    images: [{ url: "https://assets0.mirraw.com/images/10364426/IMG_0931_long_webp.webp?1688222399", alt_text: "Formal Abaya", is_default: true }],
    avg_rating: 5,
    review_count: 32,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Nida", "Silk"],
      Color: ["Black", "Maroon", "Dark Green"],
    },
    stock_quantity: 15,
    category_id: "formal",
    is_featured: true,
    is_active: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "FA-001",
  },
  {
    productId: "8",
    name: "Designer Abaya",
    slug: "designer-abaya",
    price: 8000,
    description:
      "A high-end designer abaya featuring exquisite craftsmanship and attention to detail. Perfect for those who appreciate luxury and exclusivity.",
    images: [{ url: "https://assets0.mirraw.com/images/12422106/IMG_0086_long_webp.webp?1714555159", alt_text: "Designer Abaya", is_default: true }],
    avg_rating: 5.0,
    review_count: 18,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Silk", "Chiffon"],
      Color: ["Black", "Gold", "Royal Blue"],
    },
    stock_quantity: 10,
    category_id: "formal",
    is_active: true,
    sku: "DA-001",
  },
  // Occasion
  {
    productId: "3",
    name: "Occasion Abaya",
    slug: "occasion-abaya",
    price: 6500,
    sale_price: 5999,
    description:
      "A stunning abaya designed for special occasions and celebrations. Features elegant embellishments and premium fabric for a luxurious look.",
    images: [{ url: "https://assets0.mirraw.com/images/7927519/IMG_7583_long_webp.webp?1688222433", alt_text: "Occasion Abaya", is_default: true }],
    avg_rating: 4.8,
    review_count: 24,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Silk", "Chiffon"],
      Color: ["Black", "Gold", "Burgundy"],
    },
    stock_quantity: 12,
    category_id: "occasion",
    is_featured: true,
    is_active: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "OA-001",
  },
  {
    productId: "7",
    name: "Embroidered Abaya",
    slug: "embroidered-abaya",
    price: 5500,
    sale_price: 4999,
    description:
      "A beautifully embroidered abaya featuring intricate handwork and detailed patterns. Perfect for those who appreciate artisanal craftsmanship.",
    images: [{ url: "https://assets0.mirraw.com/images/10996184/IMG_2146_long_webp.webp?1688222673", alt_text: "Embroidered Abaya", is_default: true }],
    avg_rating: 4.9,
    review_count: 21,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Navy", "Maroon"],
    },
    stock_quantity: 8,
    category_id: "occasion",
    is_active: true,
    sku: "EA-002",
  },
  // Best Sellers
  {
    productId: "9",
    name: "Classic Abaya",
    slug: "classic-abaya",
    price: 4000,
    sale_price: 3499,
    description:
      "A timeless classic abaya that never goes out of style. Features traditional design elements with a contemporary twist.",
    images: [{ url: "https://assets0.mirraw.com/images/7912677/IMG_6225_long_webp.webp?1688224065", alt_text: "Classic Abaya", is_default: true }],
    avg_rating: 4.7,
    review_count: 45,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Navy", "Gray"],
    },
    stock_quantity: 20,
    category_id: "best-sellers",
    sales_count: 120,
    is_active: true,
    sku: "CA-001",
  },
  {
    productId: "11",
    name: "Minimalist Abaya",
    slug: "minimalist-abaya",
    price: 3700,
    description:
      "A clean, minimalist abaya for those who appreciate simplicity and elegance. Features subtle design elements and premium fabric.",
    images: [{ url: "https://assets0.mirraw.com/images/11149811/IMG_2841_long_webp.webp?1674989232", alt_text: "Minimalist Abaya", is_default: true }],
    avg_rating: 4.5,
    review_count: 38,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Cotton"],
      Color: ["Black", "Gray", "Navy"],
    },
    stock_quantity: 15,
    category_id: "best-sellers",
    sales_count: 105,
    is_active: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "MA-002",
  },
  {
    productId: "14",
    name: "Classic Abaya",
    slug: "classic-abaya",
    price: 4000,
    sale_price: 3499,
    description:
      "A timeless classic abaya that never goes out of style. Features traditional design elements with a contemporary twist.",
    images: [{ url: "https://assets0.mirraw.com/images/7912677/IMG_6225_long_webp.webp?1688224065", alt_text: "Classic Abaya", is_default: true }],
    avg_rating: 4.7,
    review_count: 45,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Navy", "Gray"],
    },
    stock_quantity: 20,
    category_id: "best-sellers",
    sales_count: 120,
    is_active: true,
    sku: "CA-001",
  },
  {
    productId: "10",
    name: "Minimalist Abaya",
    slug: "minimalist-abaya",
    price: 3700,
    description:
      "A clean, minimalist abaya for those who appreciate simplicity and elegance. Features subtle design elements and premium fabric.",
    images: [{ url: "https://assets0.mirraw.com/images/11149811/IMG_2841_long_webp.webp?1674989232", alt_text: "Minimalist Abaya", is_default: true }],
    avg_rating: 4.5,
    review_count: 38,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Cotton"],
      Color: ["Black", "Gray", "Navy"],
    },
    stock_quantity: 15,
    category_id: "best-sellers",
    sales_count: 105,
    is_active: true,
    sku: "MA-002",
  },
  // New Arrivals
  {
    productId: "19",
    name: "Trendy Abaya",
    slug: "trendy-abaya",
    price: 4500,
    sale_price: 3999,
    description:
      "A fashion-forward abaya featuring the latest trends and styles. Perfect for the style-conscious woman who likes to stay ahead of the curve.",
    images: [{ url: "https://assets0.mirraw.com/images/13042629/image_long_webp.webp?1737382975", alt_text: "Trendy Abaya", is_default: true }],
    avg_rating: 4.5,
    review_count: 12,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Lilac", "Sage"],
    },
    stock_quantity: 22,
    category_id: "new-arrivals",
    created_at: new Date(),
    is_active: true,
    sku: "TA-001",
  },
  {
    productId: "20",
    name: "Contemporary Abaya",
    slug: "contemporary-abaya",
    price: 4800,
    description:
      "A contemporary abaya with modern design elements and premium fabric. Perfect for the woman who appreciates current fashion trends.",
    images: [{ url: "https://assets0.mirraw.com/images/7893678/IMG_7268_long_webp.webp?1688224062", alt_text: "Contemporary Abaya", is_default: true }],
    avg_rating: 4.7,
    review_count: 8,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Nida", "Crepe"],
      Color: ["Black", "Teal", "Dusty Rose"],
    },
    stock_quantity: 18,
    category_id: "new-arrivals",
    created_at: new Date(),
    is_active: true,
    sku: "CA-002",
  },
  {
    productId: "23",
    name: "Trendy Abaya",
    slug: "trendy-abaya",
    price: 4500,
    sale_price: 3999,
    description:
      "A fashion-forward abaya featuring the latest trends and styles. Perfect for the style-conscious woman who likes to stay ahead of the curve.",
    images: [{ url: "https://assets0.mirraw.com/images/13042629/image_long_webp.webp?1737382975", alt_text: "Trendy Abaya", is_default: true }],
    avg_rating: 4.5,
    review_count: 12,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Lilac", "Sage"],
    },
    stock_quantity: 22,
    category_id: "new-arrivals",
    created_at: new Date(),
    is_active: true,
    sku: "TA-001",
  },
  {
    productId: "124",
    name: "Trendy Abaya",
    slug: "trendy-abaya",
    price: 4500,
    sale_price: 3999,
    description:
      "A fashion-forward abaya featuring the latest trends and styles. Perfect for the style-conscious woman who likes to stay ahead of the curve.",
    images: [{ url: "https://assets0.mirraw.com/images/13042629/image_long_webp.webp?1737382975", alt_text: "Trendy Abaya", is_default: true }],
    avg_rating: 4.5,
    review_count: 12,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Nida", "Crepe"],
      Color: ["Black", "Lilac", "Sage"],
    },
    stock_quantity: 22,
    category_id: "new-arrivals",
    created_at: new Date(),
    is_active: true,
    sku: "TA-001",
  },
  // Featured
  {
    productId: "21",
    name: "Premium Abaya",
    slug: "premium-abaya",
    price: 7500,
    description:
      "A premium abaya made with the finest materials and craftsmanship. Perfect for those who demand the best in quality and design.",
    images: [{ url: "https://assets0.mirraw.com/images/8698084/IMG_2031-800x800_long_webp.webp?1688223135", alt_text: "Premium Abaya", is_default: true }],
    avg_rating: 4.7,
    review_count: 22,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Silk", "Premium Crepe"],
      Color: ["Black", "Navy", "Burgundy"],
    },
    stock_quantity: 12,
    category_id: "featured",
    is_featured: true,
    is_active: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "PA-001",
  },
  {
    productId: "22",
    name: "Luxury Abaya",
    slug: "luxury-abaya",
    price: 7000,
    sale_price: 6299,
    description:
      "A luxury abaya that combines traditional elegance with modern sophistication. Features premium materials and exquisite detailing.",
    images: [{ url: "https://assets0.mirraw.com/images/8023610/IMG_0976_long_webp.webp?1590669407", alt_text: "Luxury Abaya", is_default: true }],
    avg_rating: 4.9,
    review_count: 16,
    attributes: {
      Size: ["S", "M", "L", "XL"],
      Fabric: ["Premium Silk", "Premium Chiffon"],
      Color: ["Black", "Gold", "Emerald"],
    },
    stock_quantity: 8,
    category_id: "featured",
    is_featured: true,
    is_active: true,
    is_best_seller: true,
    is_new_arrival: true,
    sku: "LA-001",
  },
]

// Mock categories data
export const mockCategories: CategoryType[] = [
  {
    categoryId: "abayas",
    name: "Abayas",
    slug: "abayas",
    description: "Elegant and modern abayas for every occasion",
    image: "https://assets0.mirraw.com/images/5893653/AY-446-1-min_long.JPG?1710773653",
    isActive: true,
    subcategories: [
      {
        name: "Open Abayas",
        slug: "open-abayas",
        description: "Modern open abayas with stylish designs",
        image: "https://assets0.mirraw.com/images/5893653/AY-446-1-min_long.JPG?1710773653",
        isActive: true
      },
      {
        name: "Closed Abayas",
        slug: "closed-abayas",
        description: "Traditional closed abayas with contemporary touches",
        image: "https://assets0.mirraw.com/images/11960095/AB-112-JADE_GREEN_1_long_webp.webp?1697710356",
        isActive: true
      },
      {
        name: "Kaftan Abayas",
        slug: "kaftan-abayas",
        description: "Luxurious kaftan-style abayas for special occasions",
        image: "https://assets0.mirraw.com/images/11995268/CATO-ABD-075-NAVY_BLUE_1_long_webp.webp?1698929814",
        isActive: true
      }
    ]
  },
  {
    categoryId: "modest-maxi-dresses",
    name: "Modest Maxi & Dresses",
    slug: "modest-maxi-dresses",
    description: "Beautiful modest maxi dresses for every occasion",
    image: "https://assets0.mirraw.com/images/11997029/ME-AB-222-PUCE_PINK_2_long_webp.webp?1698932325",
    isActive: true,
    subcategories: [
      {
        name: "Casual Maxi Dresses",
        slug: "casual-maxi-dresses",
        description: "Comfortable and stylish maxi dresses for everyday wear",
        image: "https://assets0.mirraw.com/images/11997029/ME-AB-222-PUCE_PINK_2_long_webp.webp?1698932325",
        isActive: true
      },
      {
        name: "Formal Maxi Dresses",
        slug: "formal-maxi-dresses",
        description: "Elegant maxi dresses for formal occasions",
        image: "https://assets0.mirraw.com/images/5900026/AY-417-1-min_long.jpg",
        isActive: true
      },
      {
        name: "Party Maxi Dresses",
        slug: "party-maxi-dresses",
        description: "Stunning maxi dresses for special celebrations",
        image: "https://assets0.mirraw.com/images/11149811/IMG_2841_long.JPG",
        isActive: true
      }
    ]
  },
  {
    categoryId: "new-arrivals",
    name: "New Arrivals",
    slug: "new-arrivals",
    description: "Our latest collection of modest fashion",
    image: "https://assets0.mirraw.com/images/11997029/ME-AB-222-PUCE_PINK_2_long_webp.webp?1698932325",
    isActive: true
  },
  {
    categoryId: "best-sellers",
    name: "Best Sellers",
    slug: "best-sellers",
    description: "Our most popular modest fashion items",
    image: "https://assets0.mirraw.com/images/5900026/AY-417-1-min_long.jpg",
    isActive: true
  },
  {
    categoryId: "featured",
    name: "Featured",
    slug: "featured",
    description: "Our featured collection of modest fashion",
    image: "https://assets0.mirraw.com/images/11149811/IMG_2841_long.JPG",
    isActive: true
  }
]
